language: node_js
node_js:
  - "4"
sudo: false
before_install:
  - wget http://download.rethinkdb.com/apt/pool/precise/main/r/rethinkdb/rethinkdb_2.2.2~0precise_amd64.deb
  - ar x *.deb
  - tar xvzf data.tar.gz
before_script:
  - ./usr/bin/rethinkdb --daemon
	- sleep 10
